---
title: "Plan van aanpak Regenworm"
author: "Laisja Thomasia  & Alena"
date: "2024-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Achtergrond**

Regenwormen zijn bodembewonende wormen die behoren tot de familie Lumbricidae. Regenwormen spelen een heel belangrijke rol in het ecosysteem, vooral in de bodem.
Regenwormen zijn bekend om hun vermogen om organisch materiaal, zoals dode bladeren en plantenresten, af te breken en te verwerken tot humus, een voedzame stof die belangrijk is voor planten.
Lumbricus terrestris, ook wel de gewone regenworm of zandworm genoemd, is een van de bekendste en grootste soorten regenwormen. Volwassen Lumbricus kunnen tussen de de 20 en 30 cm lang worden, en in uitzonderlijke gevallen zelfs tot 40 cm.
Lumbricus terrestris hebben een een roze-bruine kleur en is voorzien van segmenten, met een duidelijk zichtbaar clitellum. Ze hebben ook een lichaam die cilindrisch is, met een glad oppervlak en segmenten die door een dunne slijmlaag verbonden zijn.
in dit project wordt er een genoom annotatie uitgevoerd op Lumbricus terrestris. Genoomannotatie is het proces waarbij wetenschappers de verschillende functies van de genen en andere elementen binnen het genoom van een organisme identificeren en labelen. 
Het doel van genoomannotatie is om de informatie in het DNA te begrijpen, zodat onderzoekers kunnen bepalen welke stukken van het genoom coderen voor eiwitten, welke functies deze eiwitten hebben, en hoe ze bijdragen aan de werking van de cel of het organisme.
Dit wordt uitgevoerd met de behulp van C.elegans als basemodel voor L. terrestris. Dit is omdat C. elegans goed geannoteerd is en als modelorganisme gebruikt kan worden voor de genoom annotatieprocess van Lumbricus terrestris. 
Doordat het genoom van L terrestris niet volledig geannoteerd is is het doel van dit onderzoek om een genoomannotatie uit te voeren op L. terrestris door C.elegans te gebruiken als basemodel. Dit wordt samen uitgevoerd met een positieve control om ons resultaten te verifieren. 
Er verwacht dat er veel genen homologie zal vertonen doordat L.terrestris en C.elegans een gemeenschappelijke evolutionaire oorsprong hebben. Een lage E waarde zou dit kunnen aantonen. Bij de IGV wordt er verwacht dat de exacte locaties van de homologe gen, exons en introns worden 
aangetoond. 

**Positieve controle = Lumbricus rubellus**

L. rubellus en L. terrestris behoren tot de zelfde geslacht Lumbricus. Dit betekent dat hun genetische informatie vergelijkbare genen en genfamilies bevat, ondanks het verschil in chromosoomaantal.
Dit maakt L. rubellus waardevol als referentie voor het identificeren van conservatieve genen in L. terrestris, omdat veel genen waarschijnlijk in beide soorten te vinden zullen zijn. Het genoom 
van rubellus is ook redelijk goed geanalyseerd en geannoteerd. Maar zit niet in AUGUSTUS, we kunnen dan onze eigen trainingset maken

**De Genoom annotatieproces van Lumbricus terrestris bestaat uit de volgende stappen:**

- Genoom data verkrijgen (FASTA bestanden van Lumbricus terrestris, C.elegans en positieve controle)
- Benodigde libraries installeren =  Biostrings, ggplot2, tidyverse, BLAST, GenomicRanges, Rtracklayer (AUGUSTUS moet zelf op de systeem geinstalleerd zijn "UBUNTU")
- FASTA-bestanden controleren (Biostrings)
- BLAST uitvoeren voor Alignment (BLASTR)  
- Resultaten van BLAST ( kijken naar E waarde, hits en identiteit van de overeenkomstige genen) 
- AUGUSTUS voor genoomannotatie (kijken naar sensitivity en specificity) 
- AUGUSTUS visualiseren ( IGV of kan zelfs op R met de package RTracklayer) 
- Genen verfijnen en valideren (het gebruik van Gene Ontology om de functies van de geannoteerde genen bepalen) 